[simulador]
vm-simulador ansible_host=192.168.122.216

[simulador:vars]
ansible_user=pipeline
ansible_ssh_private_key_file=~/.ssh/vm_pipeline
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
